appName: CreateSyntheticData

background:
        pathBackgroundFile: /Users/ashish/Source/Courses/Stanford/CS231N/project/repo/0/cs231n/ashish/synthetic/input/background/000002_10.png
        pathBackgroundDir: /home/schwartzd/datasets/raw/original_clipped/val
        imagesDirName: images
        annotationsDirName: labels

pathForegroundFile: /Users/ashish/Source/Courses/Stanford/CS231N/project/repo/0/cs231n/ashish/synthetic/input/foreground/plasticbags/reduced/PlasticBag01_100x100.jpeg
pathForegroundDir: /Users/ashish/Source/Courses/Stanford/CS231N/project/repo/0/cs231n/ashish/synthetic/input/foreground/basketballs/debug/Basketball
pathForegroundSuperDir: /home/schwartzd/project/cs231n/ashish/synthetic/input/foreground/single-shot-original-size/same-classes-different-images/val

pathOcclusionNameToOcclusionIdMapping: /home/schwartzd/project/cs231n/ashish/synthetic/input/occlusion-name-to-occlusion-id.csv

output:
        pathTargetDir: /home/schwartzd/datasets/intermediate/augmented/val-non-side-affixer-same-class-different-images
        imagesDirName: images
        annotationsDirName: labels

StartImageId: 13000000

threshold: 250

probabilityPrioritizeObjectsOfInterest: 0.5
probabilitySkipBackgroundImage: 0.0

affixerType: NonSideAffixer